Korzystanie z narzędzi generatywnej AI w rozwiązywaniu zadań nie jest dozwolone

<img src="no_AI.png" alt="Use of AI allowed only when properly documented " width="100" height="100">

---
# Klasyfikacja niezbalansowana
---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.metrics import roc_auc_score, average_precision_score, confusion_matrix

In [2]:
sklearn.set_config(transform_output="pandas")
sklearn.__version__

'1.7.1'

# Przykład - [Bank Marketing](https://archive.ics.uci.edu/dataset/222/bank+marketing)

W tym zadaniu użyjemy zbioru danych bankowych. Naszym celem jest przewidzenie, czy klient zdecyduje się na subskrypcję lokaty terminowej.

## Załadowanie danych

In [3]:
bank_marketing = fetch_ucirepo(id=222) 

In [4]:
X = bank_marketing.data.features 
y = bank_marketing.data.targets['y'] 

In [5]:
# # metadane
# bank_marketing.metadata

In [6]:
# # dane
# bank_marketing.variables

### Wybór cech wyjaśniających

In [7]:
X_sel = X[['balance', 'duration', 'education']]

## Wstępne przetwarzanie danych

### Brakujące dane i stopień niezbalansowania

In [8]:
len(X_sel), len(X_sel.dropna())

(45211, 43354)

Usunięcie danych nie zabiera nam wiele rekordów, ale jak wpływa to na stopień niezbalansowania?

In [9]:
y.value_counts(normalize=True) * 100

y
no     88.30152
yes    11.69848
Name: proportion, dtype: float64

In [10]:
idx = X_sel.dropna().index  # indeksy, które przetrwają
y.loc[idx].value_counts(normalize=True) * 100

y
no     88.381695
yes    11.618305
Name: proportion, dtype: float64

Bardzo nieznacznie... Dokonujemy zatem podstawienia:

In [11]:
X_sel = X_sel.loc[idx]
y_sel = y.loc[idx]

### Kodowanie zmiennej wyjaśnianej

In [12]:
label_encoder = LabelEncoder()

In [13]:
y_trans = label_encoder.fit_transform(y_sel.values)

### Kodowanie zmiennych wyjaśniających

In [14]:
enc = OneHotEncoder(drop='first', sparse_output=False)

In [15]:
X_trans = X_sel.drop(columns=['education']).join(
    enc.fit_transform(X_sel[['education']]))

## Podział na dane treningowe i walidacyjne

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_trans, y_trans,
                                                    test_size=0.2, random_state=0)

In [17]:
np.unique(y_train, return_counts=True)

(array([0, 1]), array([30625,  4058]))

## Regresja logistyczna

In [18]:
logreg = LogisticRegression(random_state=0).fit(X_train, y_train)

In [19]:
y_train_pred = logreg.predict(X_train)
y_train_pred_proba = logreg.predict_proba(X_train)[:, 1]
y_test_pred = logreg.predict(X_test)
y_test_pred_proba = logreg.predict_proba(X_test)[:, 1]

In [20]:
confusion_matrix(y_train, y_train_pred)

array([[30173,   452],
       [ 3358,   700]])

In [21]:
confusion_matrix(y_test, y_test_pred)

array([[7570,  122],
       [ 825,  154]])

In [22]:
roc_auc_score(y_train, y_train_pred_proba), roc_auc_score(y_test, y_test_pred_proba)

(0.8148638657828828, 0.8148813592993158)

In [23]:
average_precision_score(y_train, y_train_pred_proba), average_precision_score(y_test, y_test_pred_proba)

(0.40083384565216906, 0.3761873528544216)

### ENN

In [24]:
enn = EditedNearestNeighbours() 

In [25]:
X_train_enn, y_train_enn = enn.fit_resample(X_train, y_train)

In [26]:
logreg = LogisticRegression(random_state=0).fit(X_train_enn, y_train_enn)

In [27]:
y_train_pred = logreg.predict(X_train_enn)
y_train_pred_proba = logreg.predict_proba(X_train_enn)[:, 1]
y_test_pred = logreg.predict(X_test)
y_test_pred_proba = logreg.predict_proba(X_test)[:, 1]

In [28]:
confusion_matrix(y_train_enn, y_train_pred)

array([[23243,   458],
       [ 2364,  1694]])

In [29]:
confusion_matrix(y_test, y_test_pred)

array([[7156,  536],
       [ 573,  406]])

In [30]:
roc_auc_score(y_train_enn, y_train_pred_proba), roc_auc_score(y_test, y_test_pred_proba)

(0.8721683764811939, 0.8191648912126046)

In [31]:
average_precision_score(y_train_enn, y_train_pred_proba), average_precision_score(y_test, y_test_pred_proba)

(0.649549024942168, 0.37828733154743027)

Jest pewien potencjał, choć tylko na zbiorze treningowym